name: Code Quality Reports

on:
  schedule:
    # Run daily at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  coverage-report:
    name: Generate Coverage Report
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: '8'
      
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      
      - name: Run coverage
        run: pnpm run test:coverage
      
      - name: Generate coverage badge
        uses: cicirello/jacoco-badge-generator@v2
        with:
          badges-directory: badges
          generate-branches-badge: true
          generate-summary: true
      
      - name: Commit coverage badge
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'docs: update coverage badge [skip ci]'
          file_pattern: 'badges/*.svg'

  performance-tracking:
    name: Track Performance Metrics
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: '8'
      
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      
      - name: Run performance benchmarks
        run: pnpm test -- src/app/__tests__/performance.benchmark.test.tsx --reporter=json > performance-results.json
      
      - name: Store performance results
        uses: actions/upload-artifact@v4
        with:
          name: performance-history-${{ github.run_number }}
          path: performance-results.json
          retention-days: 90

  dependency-update:
    name: Check for Dependency Updates
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: '8'
      
      - name: Check for outdated packages
        run: pnpm outdated || true
      
      - name: Create issue for updates
        if: steps.outdated.outputs.has_updates == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'Dependency Updates Available',
              body: 'Automated check found outdated dependencies. Please review and update.',
              labels: ['dependencies', 'maintenance']
            })
