name: Error Tracking

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

env:
  NODE_VERSION: '20.x'

jobs:
  # Job 1: Setup Sentry
  setup-sentry:
    name: ðŸ› Setup Sentry
    runs-on: ubuntu-latest
    
    steps:
      - name: ðŸ“¥ Checkout code
        uses: actions/checkout@v4
        
      - name: ðŸ”§ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          
      - name: ðŸ“¦ Install dependencies
        run: npm ci
        
      - name: ðŸ—ï¸ Build application
        run: npm run build
        env:
          VITE_SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          VITE_ENVIRONMENT: ${{ github.ref == 'refs/heads/main' && 'production' || 'staging' }}
          
      - name: ðŸ“¤ Upload source maps to Sentry
        if: github.event_name == 'push'
        run: |
          npx @sentry/cli releases new ${{ github.sha }}
          npx @sentry/cli releases files ${{ github.sha }} upload-sourcemaps dist --rewrite
          npx @sentry/cli releases finalize ${{ github.sha }}
          npx @sentry/cli releases deploys ${{ github.sha }} new -e ${{ github.ref == 'refs/heads/main' && 'production' || 'staging' }}
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
          
  # Job 2: Error Rate Analysis
  error-analysis:
    name: ðŸ“Š Error Rate Analysis
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    
    steps:
      - name: ðŸ“Š Check error rates
        run: |
          echo "## ðŸ“Š Error Rate Analysis" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Checking error rates from Sentry..." >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "âš ï¸ **Note:** Integrate Sentry API for detailed metrics" >> $GITHUB_STEP_SUMMARY
          
  # Job 3: Create deployment in error tracking
  create-deployment:
    name: ðŸš€ Create Deployment
    runs-on: ubuntu-latest
    needs: setup-sentry
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop')
    
    steps:
      - name: ðŸš€ Notify Sentry of deployment
        run: |
          curl -X POST \
            https://sentry.io/api/0/organizations/${{ secrets.SENTRY_ORG }}/releases/${{ github.sha }}/deploys/ \
            -H "Authorization: Bearer ${{ secrets.SENTRY_AUTH_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{
              "environment": "${{ github.ref == 'refs/heads/main' && 'production' || 'staging' }}",
              "name": "Deploy ${{ github.sha }}"
            }'
